### ISSUE TITLE
Scroll back to top of ASE report no long works

### ISSUE THREAD

**Issue by PatrickDeelen** [molgenis/molgenis-ase#34]

**Comment by Mark-de-Haan** [comment]
Please check molgenis56.target.rug.nl to see if fixed.

**Comment by PatrickDeelen** [comment]
Nee hij werkt niet meer onder firefox. Onder IE werkt het wel.

*Error!* An error occurred. Please contact the administrator.
ReferenceError: event is not defined

**Comment by PatrickDeelen** [comment]
Die error krijg ik als ik op een ASE klik. Er gebeurd dan verder helemaal
niets.

**Comment by Mark-de-Haan** [comment]
Fixed the firefox bug.
Can you check again?

**Comment by Mark-de-Haan** [comment]
Fixed for Safari, Firefox and Chrome.
Can you check?

**Comment by PatrickDeelen** [comment]
Thx, firefox website is working again.

Also scroll to top is working for firefox. Only IE (of course) is giving
problems.

Shall we have a look tomorrow what IE is doing?

**Comment by Mark-de-Haan** [comment]
Can you try IE again? Focus in IE is lazy so maybe it now works with a 10 millisecond timeout

**Comment by PatrickDeelen** [comment]
Could indeed be a timing issues. Still does not work but the scroll down
takes half a second to kick in
